const imageDataThree = [
  {
    id: "bo7855",
    title: "Long jacket",
    designer: "Jamie lanster",
    starNum: 5,
    quantity: 8,
    price: 685.99,
    manufaPlace: "Awesome for copule day",
    imagePath: "public/img/cloth13.jfif",
    type: "m-fash",
  },
  {
    id: "wo45866",
    title: "Small Dress",
    designer: "Lesile menuzeure",
    starNum: 3,
    quantity: 4,
    price: 385.99,
    manufaPlace: "For Parentes Day",
    imagePath: "public/img/cloth13.jfif",
    type: "w-fash",
  },
  {
    id: "adg12586",
    title: "Skinny Dress",
    designer: "Samuel Tale",
    starNum: 5,
    quantity: 7,
    price: 950.5,
    manufaPlace: "Brand new Froom Ethiopia",
    imagePath: "public/img/cloth9.jfif",
    type: "w-fash",
  },
  {
    id: "le4522",
    title: "Leather Jacket",
    designer: "John smith",
    starNum: 4,
    quantity: 5,
    price: 750.5,
    manufaPlace: "Best quality Leather",
    imagePath: "public/img/cloth10.jfif",
    type: "m-fash",
  },
  {
    id: "long7856",
    title: " Fashion Shoe",
    designer: "Habtamu befkadu",
    starNum: 5,
    quantity: 7,
    price: 1150.5,
    manufaPlace: "Best quality Dress ",
    imagePath: "public/img/shoe6.jfif",
    type: "w-fash",
  },
  {
    id: "ra78522",
    title: "Rain Jacket",
    designer: "Pinky Blinedrs",
    starNum: 5,
    quantity: 8,
    price: 554.99,
    manufaPlace: "Awesome for rainy day",
    imagePath: "public/img/cloth7.jfif",
    type: "m-fash",
  },
  {
    id: "bo4522",
    title: "Boofy Jacket",
    designer: "Unknown Designer",
    starNum: 4,
    quantity: 8,
    price: 854.99,
    manufaPlace: "Awesome for copule day",
    imagePath: "public/img/cloth11.jfif",
    type: "m-fash",
  },
  {
    id: "gdh4756",
    title: "Boofy Jacket",
    designer: "Unknown Designer",
    starNum: 4,
    quantity: 8,
    price: 854.99,
    manufaPlace: "Awesome for copule day",
    imagePath: "public/img/images.jfif",
    type: "m-access",
  },
  {
    id: "asdd42866",
    title: "Boofy Jacket",
    designer: "Unknown Designer",
    starNum: 4,
    quantity: 8,
    price: 854.99,
    manufaPlace: "Awesome for copule day",
    imagePath: "public/img/cloth18.jfif",
    type: "m-access",
  },
  {
    id: "asdd42866",
    title: "Boofy Jacket",
    designer: "Unknown Designer",
    starNum: 4,
    quantity: 8,
    price: 854.99,
    manufaPlace: "Awesome for copule day",
    imagePath: "public/img/cloth16.jfif",
    type: "m-access",
  },

  {
    id: "gh58531",
    title: "Boofy Jacket",
    designer: "Unknown Designer",
    starNum: 4,
    quantity: 8,
    price: 854.99,
    manufaPlace: "Awesome for copule day",
    imagePath: "public/img/cloth14.jfif",
    type: "m-fash",
  },
  {
    id: "dgh475612",
    title: "Air-Max",
    designer: "Unknown Designer",
    starNum: 4,
    quantity: 12,
    price: 454.99,
    manufaPlace: "confurtable",
    imagePath: "public/img/shoe2.jfif",
    type: "w-fash",
  },
  {
    id: "dgh475612",
    title: "Air-Max",
    designer: "Unknown Designer",
    starNum: 4,
    quantity: 12,
    price: 454.99,
    manufaPlace: "confurtable",
    imagePath: "public/img/person5.jpg",
    type: "w-access",
  },
]

export default imageDataThree
